services:
  app_db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
networks:
    app_network:
        driver: bridge
volumes:
    db_data: